### PR TITLE
Support camel case convention

### PR DESCRIPTION
**Pull request by tgeorgel**
Adding a ucfirst allow using camel case convention : 

```
$client->document()->methodName();
$client->bankDeposit()->methodName();
```

### CODE REVIEW

**Comment by frenchcomp** [comment]
Hi,
Thanks you for your contribution, but can you write tests to confirm no BC Breaks ?
Have a nice day

Richard

**Comment by tgeorgel** [comment]
Hey @frenchcomp,

I added lowerCamelCase test to the `SellsyTest::testDefinitions()` suite.

FYI, the README says that you can use PHP 7.4+ but your package `teknoo/immutable` seems to be only supporting PHP 8.0+.
Strange that i got the problem only when running composer directly on the package...

```
  Problem 1
    - teknoo/immutable[2.0.9, ..., 2.0.12] require php ~8.0 -> your php version (7.4.28) does not satisfy that requirement.
    - teknoo/immutable[3.0.0, ..., 3.0.1] require php ^8.1 -> your php version (7.4.28) does not satisfy that requirement.
    - Root composer.json requires teknoo/immutable ^2.0.9||^3.0 -> satisfiable by teknoo/immutable[2.0.9, 2.0.10, 2.0.11, 2.0.12, 3.0.0, 3.0.1].
```

Anyways, switched to 8.1 for running the tests.
Thanks for your work ! :)

**Comment by frenchcomp** [comment]
Hi,
Thank very much, but I'd rather you add new tests (aka add new methods "testDefinitionInCamelCase" and "testDefinitionInvokeInCamelCase") rather than modify existing tests. 
The tests are there to make sure there are no BC Breaks, so you can't modify the old tests that validate the old behavior.

About immutable, thanks, i will restore support of Immutable 2+.

Have a nice day.

**Comment by frenchcomp** [comment]
Hi,
I merge via my CI your PR and fix yours tests.
A new version was released today.
So : Github will show this PR has closed and not merged, but it  was merged ans squashed by my own CI Tools

About teknoo/immutable. The constraint is already defined on 2.0.9+ or 3.0+, if you run the command `composer update` with PHP 7.4 or 8.0, Immutable 2.0.9 will be selected by composer.

Have a nice day and thanks for your PR.

Richard

**Comment by tgeorgel** [comment]
Hi Richard,

Sorry, didn't have the time recently to finish correcting the tests...
Glad your merged it, and thanks again for your work !

Have a nice day as well.

Thomas

**Pull request closed without merging**
