### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by QuentinMaypic**

### CODE REVIEW

**Comment by frenchcomp** [comment]
Sorry, but there are no descriptions, no tests and you pull on a deprecated branch/version.

**Comment by frenchcomp** [comment]
And why a "Webapic Client" ? 
It's probably own to your business domain :). (You can just add the new method directly into the client).

**Comment by QuentinMaypic** [comment]
Sorry, I just wanted to fork your repo and push these modifications into mine (without sending a pull request).
Best regards,

**Comment by frenchcomp** [comment]
No problem, have a nice day :)

**Comment by QuentinMaypic** [comment]
Hi, just so you know, we use the version 1.0.0 because the last version is not compatible with Prestashop 1.7.6 with guzzle 5.0 max. I tried to upgrade it in prestashop but it broked almost everything... :p Have a nice day too !

**Comment by frenchcomp** [comment]
Hi, ok, I work on a new major release, Guzzle will be not mandatory :).
Thanks for the feedback

**Pull request closed without merging**
